OPTIONS(skip=1)
LOAD DATA 
   APPEND INTO table  NETWORK_MV38_DATA

  fields terminated by ","
  optionally enclosed by '"'   
  TRAILING NULLCOLS (
NAME,
TYPE,
DRIRECTIONALITY,
WORKER_PROT_STATE,
OPER_STATE,
SERVICE_STATE,
PROTECTION,
ASON_STATE,
UPLOAD_DATE "SYSDATE" )
