OPTIONS(skip=1)
LOAD DATA 
   APPEND INTO table  NETWORK_NQRT_EXTRACT
  fields terminated by ","
  optionally enclosed by '"'   
  TRAILING NULLCOLS (
NAME,
TYPE,
WORKER_STATE,
OPERATIONAL_STATE,
SERVICE_STATE,
PROTECTION,
ASTN_STATE,
DATE_ADDED "SYSDATE" )
