SET PAGES 0;
SET LINES 32767;
SET TRIMS ON;
SET ECHO OFF;
SET WRAP OFF;
SET TRIMSPOOL ON;
SET FEEDBACK OFF;
SET TERM OFF;
SET HEAD OFF;
SET VERIFY OFF;
SET TIMING OFF;
SET HEADING OFF;
SET LINESIZE 500000;
SET NUMWIDTH 20;
SET NUMFORMAT 999999999999999999999999;
SET LONG 50000;
COLUMN TXT FORMAT A30;
SET LONGCHUNKSIZE 30000;
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI:SS';
spool /opt/ontology/scripts/manual_service_upload/process/Manual_Services_raw.csv;
SELECT '"'||TRIM(Service_ID)||'",'||'"'||TRIM(Nominated_Party)||'",'||'"'||TRIM(SF_Acc_Name)||'",'||'"'||TRIM(Prov_Customer)||'",'||'"'||TRIM(Inv_Customer)||'",'||'"'||TRIM(NPID)||'",'||'"'||TRIM(PID)||'",'||'"'||TRIM(Batch_ID)||'",'||'"'||TRIM(Sub_Group)||'",'||'"'||TRIM(Batch_Status)||'",'||'"'||TRIM(Market)||'",'||'"'||TRIM(Sector)||'",'||'"'||TRIM(SF_Acc_MSC)||'",'||'"'||TRIM(Regional_Head)||'",'||'"'||TRIM(Micro_Segment)||'",'||'"'||TRIM(SERVICE_PROJECT)||'",'||'"'||TRIM(Current_Gate)||'",'||'"'||TRIM(Opp_Reference)||'",'||'"'||TRIM(Opp_Proposed_Date)||'",'||'"'||TRIM(Initial_Opp_Value)||'",'||'"'||TRIM(Currency)||'",'||'"'||TRIM(Opp_Acc_Mgr)||'",'||'"'||TRIM(Opp_Soln_Arch)||'",'||'"'||TRIM(Legacy_Name)||'",'||'"'||TRIM(Legacy_Product)||'",'||'"'||TRIM(Suggested_Hero_Product)||'",'||'"'||TRIM(Forecast_Hero_Volume)||'",'||'"'||TRIM(Forecast_Provide_Date)||'",'||'"'||TRIM(Forecast_Cease_Date)||'",'||'"'||TRIM(Soln_Arch_Comment)||'",'||'"'||TRIM(Approach)||'",'||'"'||TRIM(Batch_Comments)||'",'||'"'||TRIM(Cease_Letter_Target_Date)||'",'||'"'||TRIM(Soft_Cease_Action)||'",'||'"'||TRIM(Hard_Cease_Action)||'",'||'"'||TRIM(Cease_Order_Reference)||'",'||'"'||TRIM(Cease_Order_Status)||'",'||'"'||TRIM(Provisioning_Order_Reference)||'",'||'"'||TRIM(Provisioning_Order_Status)||'",'||'"'||TRIM(On_Hold_Reason)||'",'||'"'||TRIM(Resubmission_Date)||'",'||'"'||TRIM(Indirect_Direct)||'",'||'"'||TRIM(Reseller)||'",'||'"'||TRIM(SF_System)||'",'||'"'||TRIM(SF_Owner)||'",'||'"'||TRIM(SF_Owner_Email)||'",'||'"'||TRIM(Provisioning_Status)||'",'||'"'||TRIM(Billing_Status)||'",'||'"'||TRIM(Inventory_Status)||'",'||'"'||TRIM(Network_Status)||'",'||'"'||TRIM(BT_Status)||'",'||'"'||TRIM(CONTRACT_ITEMS_TLD)||'",'||'"'||TRIM(Provisioning_System)||'",'||'"'||TRIM(Provisioning_Circuit_Count)||'",'||'"'||TRIM(PROVISIONING_CIRCUIT_REFS)||'",'||'"'||TRIM(Billing_System)||'",'||'"'||TRIM(Billing_Acc_No)||'",'||'"'||TRIM(Latest_Bill_Date)||'",'||'"'||TRIM(Billing_Service_ID)||'",'||'"'||TRIM(Inventory_System)||'",'||'"'||TRIM(Inventory_Circuit_Count)||'",'||'"'||TRIM(INVENTORY_CIRCUIT_REFS)||'",'||'"'||TRIM(Network_Circuit_Count)||'",'||'"'||TRIM(Network_Circuit_Refs)||'",'||'"'||TRIM(Network_Switch_Name)||'",'||'"'||TRIM(Provisioning_OLO_Ref)||'",'||'"'||TRIM(Inventory_OLO_Ref)||'",'||'"'||TRIM(BT_OLO_REF)||'",'||'"'||TRIM(BT_Latest_Invoice_Date)||'",'||'"'||TRIM(Site_Address)||'",'||'"'||TRIM(Analysis_Status)||'",'||'"'||TRIM(Analysis_Comments)||'",'||'"'||TRIM(Order_Number)||'",'||'"'||TRIM(Associated_Orders)||'",'||'"'||TRIM(MANUAL_CONTRACT_ITEMS_TLD)||'",'||'"'||TRIM(Manual_Contract_Item_Status)||'",'||null||'",'||'"'||TRIM(SF_Acc_ID)||'",'||'"'||TRIM(SF_Owner_ID)||'",'||'"'||TRIM(DDI_Range)||'",'||null||'",'||'"'||TRIM(Contractual_Customer)||'",'||'"'||TRIM(Billing_Customer)||'",'||'"'||TRIM(Delivery_Customer)||'",'||'"'||TRIM(Closed_Loss_Analysis)||'",'||'"'||TRIM(TES_Forecast_Date)||'",'||null||'",'||'"'||TRIM(Network_Audit_Date)||'",'||'"'||TRIM(Billing_Service_Ref)||'",'||'"'||TRIM(Data_Extraction_Date)||'""' FROM PRT_E_MANUAL_SERVICE;
SPOOL OFF;
EXIT;
